### ISSUE TITLE
Opengraph image is too large

### ISSUE THREAD

**Issue by nalakawula** [maelstrom-cms/odin#11]
Opengraph image result is too large "scaled up". I dont know how to discribe this, so I include secrenshot as attachment. The actual image size is 200x200.

https://ibb.co/310S1tK

**Comment by OwenMelbz** [comment]
Hi!

Sorry about this, must be quite annoying.

This is a bit tricky to find a valid solution for, most systems recommend an open graph image of 1200x630

If the above dimensions are used, then the problem does not present itself as it scales accordingly.

One of the reasons we built this tool was help us identify problems - and ironically the fact the image is displaying massive and pixelated highlights (for us) there is a problem with the open graph images, thus it gives us an action point to fix for our clients.

So rather than us "hiding the problem" on the tool, we would prefer to make it obvious something is wrong so we can fix it.

With that being said - we won't be fixing this as it helps us spot problems.

You can always just edit the HTML yourself. e.g. The current HTML has:

```html
<img class="w-full h-auto shadow-lg" src="https://www.website.com/open-graph.jpg" alt="website title">
```

You can replace the `w-full` with `max-w-full` then it shouldn't upscale the image to the container width.
