### ISSUE TITLE
Unable to create/edit website with Cron monitoring enabled

### ISSUE THREAD

**Issue by srichter** [maelstrom-cms/odin#6]
`WebsiteController` checks for a field `cron_keyword` when validating the request in the store/update methods, but the text input's actual name is `cron_key`. Opening PR.

**Comment by OwenMelbz** [comment]
Hey thanks for this, I think I got lazy and rush changed some things via github directly (including this). Proves shouldn’t rush otherwise you’ll just screw up 😂

**Comment by srichter** [comment]
No worries! Another issue I've noticed is that the displayed cron ping URLs are invalid when creating a site, as the site doesn't have an id yet. Might not make sense to show the URLs there.

I plan to implement notifications if crons are not pinged within a defined timeframe; would you be interested in a PR for that?

**Comment by OwenMelbz** [comment]
Good catch :) that was the last thing I added quickly as we had some cron issues.

Regarding notifications - this is something I’d be interested in, however it would need to be something really simple, currently it works well because you can add an extra payload to help identify each scheduled task. However if we start adding defined timeframes you’d need to be able to assign each rule to different scheduled tasks, which then adds a complexity.

Have you got any ideas how to keep it super simple both at UI and implementation level to support multiple jobs?

**Comment by srichter** [comment]
My initial ideas would be:

- Define a single timeframe per website, which would only allow for rudimentary monitoring that _any_ tasks are firing/completing.

- Define the timeframe in each ping and use the last ping of that tasks's timeframe for determining when the next should occur

**Comment by OwenMelbz** [comment]
So if you needed to make sure a scheduled task runs every minute, how would you define that in the UI?

**Comment by srichter** [comment]
For the first option I'd just have another input to define the timeframe.

For the second option I'd use a URL parameter such as `nextping` and the scheduled checker task would look through the past cron pings for ones containing that key in their payload and check to see if any of the are late. The tricky part would be determining how far back the checker  looks to identify unique pings (maybe combine it with the first option to define the longest timeframe?).

**Comment by OwenMelbz** [comment]
I think i'd more likely accept a PR that uses the query string method, that way the feature is 100% opt-in and allows the ability from the word go to support multiple jobs.

The reason I say this is because primarily this is a tool that my company use, and our priority is that it works for us, anything that we introduce we'll have to maintain for the next X years within business hours, so we need to make sure it aligns with our goals.

So if you can solve it using query strings, then 👍🏽

**Comment by srichter** [comment]
Sounds good. I'll see how I end up implementing it for my own use and then open a PR and we can go from there.
